apiVersion: v1
kind: Service
metadata:
  app: mysql
  tier: backend
spec:
  selector:
    app: mysql
    tier: backend
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306