apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    app: wordpress
    tier: backend
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306