# Initial Deployment of a multi-container Nginx Pod with a Readiness Probe 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      volumes:
        - name: www-data-share
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx:1.7.9
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www-data-share
              readOnly: true
          readinessProbe:  # Is the application ready to serve traffic?
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0 # Number of seconds after the container has started before the probe is initiated.
            periodSeconds: 2    # How often, in seconds, to perform the probe. Defaults to 10 seconds. Min value is 1.
            timeoutSeconds: 1   # Number of seconds after which the probe times out. Defaults to 1 second
            successThreshold: 1 # Minimum consecutive successes for the probe to be considered successful after having failed
            failureThreshold: 3 # When a Pod starts and the probe fails,
                                # Kubernetes will try failureThreshold times before giving up
                                # In case of readiness probe failure, the Pod will be marked Unready. 
                                # Defaults to 3. Minimum value is 1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        # Second Git Sync Container
        - name: git-sync
          image: openweb/git-sync:0.0.1
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www-data-share
          env:                     
            - name: GIT_SYNC_REPO  
              value: "https://github.com/naveenjoy/naveenjoy.github.io.git"
            - name: GIT_SYNC_DEST
              value: "/usr/share/nginx/html" 
            - name: GIT_SYNC_BRANCH
              value: "master"
            - name: GIT_SYNC_REV
              value: "FETCH_HEAD"
            - name: GIT_SYNC_WAIT
              value: "10"