# Rollout a new version of Nginx in the multi-container deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
      annotations: 
        kubernetes.io/change-cause: "Updated Nginx to 1.11.9"  # Deployment will record this info and trigger a new rollout
    spec:
      volumes:
        - name: www-data-share
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx:1.11.9     #Update software from 1.7.9 to 1.11.9 using a RollingUpdate Strategy
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www-data-share
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        # Second Git Sync Container
        - name: git-sync
          image: openweb/git-sync:0.0.1
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www-data-share
          env:                     
            - name: GIT_SYNC_REPO  
              value: "https://github.com/naveenjoy/naveenjoy.github.io.git"
            - name: GIT_SYNC_DEST
              value: "/usr/share/nginx/html" 
            - name: GIT_SYNC_BRANCH
              value: "master"
            - name: GIT_SYNC_REV
              value: "FETCH_HEAD"
            - name: GIT_SYNC_WAIT
              value: "10"