# Rollout a new version of Nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:  
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  template:
    annotations:  # change-cause annotations are added to the template and *Not* to the deployment 
      kubernetes.io/change-cause: "Updated Nginx to 1.11.9"  # Deployment will record this info and trigger a new rollout
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.11.9     #Update software from 1.7.9 to 1.11.9 using a RollingUpdate Strategy
          imagePullPolicy: Always
          ports:
            - containerPort: 80