apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: my-nginx
  annotations:
    build-url: http://my-build-url.com/jobs/10
    supported-by: 1-888-222-1803
spec:
  volumes:            # Define all the volumes available to your containers
    - name: www-data  # Name the volume
      emptyDir: {}    # Creates a new directory. It will exist as long as the Pod is running on the node.
                      # It can persist data across container failures and restarts.
                      # Data will not persist if the node dies and the pod moves to another node.
  containers:
    - name: nginx
      image: nginx:1.13.8
      volumeMounts:  # Mount volumes within a container definition using volumeMounts
        - mountPath: /srv/www  # Mount path within the container
        name: www-data         # Name must match the volume name defined above in the Volumes section
        readOnly: true         # Volume can be marked as readOnly if the container doesn't need to write to it 
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 3 
      resources:
        requests:
          cpu: "500m"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      ports:
      - containerPort: 80

