apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: my-nginx
  annotations:
    description: Nginx container with an AWS EBS Persistent Volume
spec:
  volumes:
    - name: www-data-ebs        # Name of the AWS EBS Volume 
      persistentVolumeClaim:    # Pods access dynamic AWS storage by using the claim as a volume
        claimName: aws-claim    # Must match the name of the AWS Persistent Volume Claim we created
  containers:
    - name: nginx
      image: nginx:1.13.8
      volumeMounts:
        - mountPath: /srv/www    # Mount path within the container
        name: www-data-ebs       # Name must match the AWS EBS volume name defined above in the Volumes section
        readOnly: true           # The container can only read data from this volume
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 3 
      resources:
        requests:
          cpu: "500m"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      ports:
      - containerPort: 80

