apiVersion: v1
kind: Pod 
metadata: 
  name: nginx 
  labels:
    app: my-nginx 
spec:  
  containers:
  - name: nginx       
    image: nginx:1.13.8   # Updated Docker image version from 1.7.9 to 1.13.8
    ports:
    - containerPort: 80
