# This specification will create a new Service object named “my-nginx-service” which targets TCP port 80
# on any Pod with the "tier=frontend" label
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx      # Pod's label targeted by this service
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80        # Incoming port
      targetPort: 80  # Port exposed by the pod.
 # For services of type=NodePort, the Kubernetes master will allocate a port 
 # from 30000-32767 (default), and each Node will proxy 
 # that port (the same port number on every Node) into your Service. 
 # That port will be reported in your Service’s spec.ports[*].nodePort field.
  type: NodePort