kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations: {}
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  # Creates an AWS ELB
  type: LoadBalancer
  # For security, you can uncomment the below lines to permit only certain source CIDR ranges
  # loadBalancerSourceRanges:
  #  - 10.0.0.0/8