apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    tier: frontend 
spec:  
  containers:
    - name: nginx       
      image: nginx:1.13.8   	# Update the nginx container from Ver. 1.7.9 to 1.13.8
      ports:
        - containerPort: 80
      imagePullPolicy: Always   # Always force an image pull.
                                # Allows us to watch the upgrade process every time we do this lab. 
                                # The default image pull policy is IfNotPresent.
                                # Kubelet by default, will skip pulling an image if it's locally present.
